service: kegerator-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  temp:
    handler: handler.temp
    environment:
      DEVICE_ID: ${ssm:kegerator-device-id}
      PARTICLE_TOKEN: ${ssm:particle-api-key}
    events:
      - http: GET temp
    cors:
      origins:
        - '*'
      headers:
        - Content-Type
        - Authorization
